# Generated by Django 3.1.2 on 2020-11-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=250)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.SmallAutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=25, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_time', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
                ('create_user', models.IntegerField(blank=True, db_column='create_user', null=True)),
                ('update_user', models.IntegerField(blank=True, db_column='update_user', null=True)),
                ('delete_flag', models.IntegerField(blank=True, db_column='delete_flag', null=True)),
            ],
            options={
                'db_table': 'product_types',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('user_name', models.CharField(blank=True, db_column='user_name', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=100, null=True)),
                ('enable', models.IntegerField(blank=True, db_column='enable', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_time', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
                ('create_user', models.IntegerField(blank=True, db_column='create_user', null=True)),
                ('update_user', models.IntegerField(blank=True, db_column='update_user', null=True)),
                ('delete_flag', models.IntegerField(blank=True, db_column='delete_flag', null=True)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='home.role')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ProductTranslate',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_time', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
                ('create_user', models.IntegerField(blank=True, db_column='create_user', null=True)),
                ('update_user', models.IntegerField(blank=True, db_column='update_user', null=True)),
                ('delete_flag', models.IntegerField(blank=True, db_column='delete_flag', null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('product_type_id', models.ForeignKey(db_column='product_type_id', on_delete=django.db.models.deletion.CASCADE, to='home.producttype')),
            ],
            options={
                'db_table': 'product_translates',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('product_type', models.IntegerField(blank=True, db_column='product_type', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_time', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
                ('create_user', models.IntegerField(blank=True, db_column='create_user', null=True)),
                ('update_user', models.IntegerField(blank=True, db_column='update_user', null=True)),
                ('delete_flag', models.IntegerField(blank=True, db_column='delete_flag', null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.SmallAutoField(db_column='id', primary_key=True, serialize=False)),
                ('discount', models.FloatField(blank=True, db_column='discount', null=True)),
                ('effected_start_date', models.DateTimeField(blank=True, db_column='effected_start_date', null=True)),
                ('effected_end_date', models.DateTimeField(blank=True, db_column='effected_end_date', null=True)),
                ('activation', models.IntegerField(blank=True, db_column='activation', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_time', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
                ('create_user', models.IntegerField(blank=True, db_column='create_user', null=True)),
                ('update_user', models.IntegerField(blank=True, db_column='update_user', null=True)),
                ('delete_flag', models.IntegerField(blank=True, db_column='delete_flag', null=True)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
            options={
                'db_table': 'discount',
            },
        ),
    ]
