# Generated by Django 3.1.2 on 2020-12-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201124_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.IntegerField(blank=True, db_column='rank', null=True),
        ),
    ]
