# Generated by Django 3.1.2 on 2020-12-31 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201230_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='home.product'),
        ),
        migrations.AlterField(
            model_name='producttranslate',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='all_product', to='home.product'),
        ),
    ]
