# Generated by Django 3.1.2 on 2021-01-02 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201231_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(blank=True, db_column='create_time', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_column='update_time', null=True)),
                ('create_user', models.IntegerField(blank=True, db_column='create_user', null=True)),
                ('update_user', models.IntegerField(blank=True, db_column='update_user', null=True)),
                ('delete_flag', models.IntegerField(blank=True, db_column='delete_flag', default=0)),
                ('customer_id', models.IntegerField(blank=True, db_column='discount', null=True)),
                ('order_date', models.DateTimeField(blank=True, db_column='effected_end_date')),
                ('order_status', models.IntegerField(db_column='activation', default=1)),
                ('product_id', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='order', to='home.product')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
