# Generated by Django 3.1.2 on 2021-03-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210103_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(db_column='amount', default=1000),
            preserve_default=False,
        ),
    ]
