# Generated by Django 3.1.2 on 2021-03-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(db_column='quantity', default=1000),
            preserve_default=False,
        ),
    ]
